# Generated by Django 2.0.6 on 2018-06-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_sku', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=200)),
            ],
        ),
    ]
