# Generated by Django 2.0.6 on 2018-06-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180606_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='content_file_name/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='content_file_name/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='content_file_name/'),
        ),
    ]
