# Generated by Django 2.0.6 on 2018-06-08 15:06

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20180608_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img1',
            field=models.ImageField(blank=True, default='', null=True, upload_to=product.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img2',
            field=models.ImageField(blank=True, default='', null=True, upload_to=product.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img3',
            field=models.ImageField(blank=True, default='', null=True, upload_to=product.models.content_file_name),
        ),
    ]
