# Generated by Django 2.0.6 on 2018-06-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20180608_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_content',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
